<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pt-br" lang="pt-br">
<head>
    <title>FEDERAL - Aplicações</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <link rel="shortcut icon" href="federal.ico" type="image/x-icon" />
    <meta name="description" content="federal - Aplicações" />
    <meta name="keywords" content="federal, PHP" />
    <meta name="author" content="Edmilson Messias Quintino" />

    <link type="text/css" href="css/redmond/jquery-ui-1.8.16.custom.css" rel="stylesheet" />
    <link href="css/style.css" rel="stylesheet" type="text/css" />
    <link href="css/layout.css" rel="stylesheet" type="text/css" />

    <script type="text/javascript" src="js/jquery-1.6.2.min.js"></script>
    <script type="text/javascript" src="js/jquery-ui-1.8.16.custom.min.js"></script>
    <script type="text/javascript" src="js/script.js"></script>
</head>
<body class="sinistro">
    <div id="header_cadastro">
        <ul>
            <li><a href="#"><img src="img/excluir.png" height="18px" /></a></li>
            <li><a href="#"><img src="img/inicio_des.png" height="18px"  /></a></li>
            <li><a href="#"><img src="img/voltar_des.png" height="18px"  /></a></li>
            <li><a href="#"><input type="text" name="pagina" size="5" maxlength="4"/></li>
            <li><a href="#"><label>de 1</label></a></li>
            <li><a href="#"><img src="img/avancar.png" height="18px"  /></a></li>
            <li><a href="#"><img src="img/ultimapag.png" height="18px"  /></a></li>
            <li><a href="#"><img src="img/mais.png" height="18px"  /></a></li>
            <li><a href="#"><img src="img/disquete.png" height="18px"  /></a></li>
        </ul>
    </div>
    <div id="conteudo_cadastro">
        
    </div>
</body>
</html>