<?php ?>
<h1>Bem-vindo!</h1>

<p class="p">Bem-vindo ao programa de Rgistro de <b>Processos de Sinistro</b>.</p>
<p>Este programa tem como objetivo a organização do <b>QUADRO DE CREDORES</b></p>
	<br>
<ul class="p">
    <li>Registro de Processos de Sinistro;</li>
    <li>Acompanhamento de Processos Judiciais;</li>
    <li>Organização do Quadro de Credores.</li>
</ul>
<p class="p"></p>
<p class="p"><b></b></p>
